// import { auth } from "@/auth";
import Layout from "@/components/layouts/Layout";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // сессион провайдер нужен чтобы получать сессию на клиенте,
  // но что-то он работает как-то не оч

  // const session = await auth();

  return (
    // <SessionProvider session={session}>
    <html lang="ru">
      <body
      // className="
      //   flex flex-col justify-start
      //   max-w-[1012px]
      //   [@media(pointer:coarse)]:max-w-[500px] mx-auto
      //   items-start [@media(pointer:coarse)]:items-center
      // "
      >
        <Layout>{children}</Layout>
      </body>
    </html>
    // </SessionProvider>
  );
}
