import Layout from "@/components/layouts/Layout";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body
      // className="
      //   flex flex-col justify-start
      //   max-w-[1012px]
      //   [@media(pointer:coarse)]:max-w-[500px] mx-auto
      //   items-start [@media(pointer:coarse)]:items-center
      // "
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
